
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



NEX_HACK_UPDATE = '/nex/gui/client_template/nex_hack_update'
NEX_NET_UPDATE = '/nex/gui/client_template/nex_net_update'
UPDATE = '/nex/gui/client_template/update'