
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



DIRTY = '/nex/gui/client/dirty'
GUI_VISIBLE = '/nex/gui/client/gui_visible'
HAS_OPTIONAL_GUI = '/nex/gui/client/has_optional_gui'
MESSAGE = '/nex/gui/client/message'
NEW = '/nex/gui/client/new'
PROGRESS = '/nex/gui/client/progress'
NEX_HACK_UPDATE = '/nex/gui/client/nex_hack_update'
NEX_NET_UPDATE = '/nex/gui/client/nex_net_update'
STATUS = '/nex/gui/client/status'
STILL_RUNNING = '/nex/gui/client/still_running'
SWITCH = '/nex/gui/client/switch'
UPDATE = '/nex/gui/client/update'