
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import patchbay

ABORT_COPY = '/nex/server/abort_copy'
ABORT_PARRALLEL_COPY = '/nex/server/abort_parrallel_copy'
ABORT_SNAPSHOT = '/nex/server/abort_snapshot'
ASK_FOR_PATCHBAY = '/nex/server/ask_for_patchbay'
PATCHBAY_DAEMON_READY = '/nex/server/patchbay_daemon_ready'
'''The patchbay daemon sends this message to the daemon
when it is ready to receive custom names'''

CHANGE_ROOT = '/nex/server/change_root'
CLEAR_CLIENT_TEMPLATES_DATABASE = '/nex/server/clear_client_templates_database'
CONTROLLER_ANNOUNCE = '/nex/server/controller_announce'
CONTROLLER_DISANNOUNCE = '/nex/server/controller_disannounce'
EXOTIC_ACTION = '/nex/server/exotic_action'
GET_SESSION_PREVIEW = '/nex/server/get_session_preview'
GUI_ANNOUNCE = '/nex/server/gui_announce'
GUI_DISANNOUNCE = '/nex/server/gui_disannounce'
HAS_OPTION = '/nex/server/has_option'
HIDE_SCRIPT_INFO = '/nex/server/hide_script_info'
LIST_FACTORY_CLIENT_TEMPLATES = '/nex/server/list_factory_client_templates'
LIST_PATH = '/nex/server/list_path'
LIST_SESSION_TEMPLATES = '/nex/server/list_session_templates'
LIST_SESSIONS = '/nex/server/list_sessions'
LIST_USER_CLIENT_TEMPLATES = '/nex/server/list_user_client_templates'
MONITOR_ANNOUNCE = '/nex/server/monitor_announce'
MONITOR_QUIT = '/nex/server/monitor_quit'
NEW_SESSION = '/nex/server/new_session'
OPEN_FILE_MANAGER_AT = '/nex/server/open_file_manager_at'
OPEN_SESSION = '/nex/server/open_session'
OPEN_SESSION_OFF = '/nex/server/open_session_off'
QUIT = '/nex/server/quit'
REMOVE_CLIENT_TEMPLATE = '/nex/server/remove_client_template'
RENAME_SESSION = '/nex/server/rename_session'
SAVE_SESSION_TEMPLATE = '/nex/server/save_session_template'
SCRIPT_INFO = '/nex/server/script_info'
SCRIPT_USER_ACTION = '/nex/server/script_user_action'
SET_NSM_LOCKED = '/nex/server/set_nsm_locked'
SET_OPTION = '/nex/server/set_option'
SET_OPTIONS = '/nex/server/set_options'
SET_TERMINAL_COMMAND = '/nex/server/set_terminal_command'
EXPORT_CUSTOM_NAMES = '/nex/server/export_custom_names'
'Export the custom names of clients and ports to JACK pretty-name metadatas'

IMPORT_PRETTY_NAMES = '/nex/server/import_pretty_names'
'''Import the pretty names from JACK metadatas to custom names.
Useful if you want to save in session metadatas written by another program.'''

CLEAR_PRETTY_NAMES = '/nex/server/clear_pretty_names'
'''Clear all the JACK pretty-name metadatas, except theses ones exported by
auto_export_custom_names if it is set.'''

AUTO_EXPORT_CUSTOM_NAMES = '/nex/server/auto_export_custom_names'
'''Enable/disable auto-export of ports and clients custom names
to JACK pretty-name metadatas (arg types: i)'''
