
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



DETAILS = '/nex/gui/listed_session/details'
SCRIPTED_DIR = '/nex/gui/listed_session/scripted_dir'