
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import client

CLEAR = '/nex/gui/preview/clear'
NOTES = '/nex/gui/preview/notes'
SESSION_SIZE = '/nex/gui/preview/session_size'
SNAPSHOT = '/nex/gui/preview/snapshot'
STATE = '/nex/gui/preview/state'