
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.

from . import monitor

ACTIVATE_DSP_LOAD = '/nex/patchbay/activate_dsp_load'
ACTIVATE_TRANSPORT = '/nex/patchbay/activate_transport'
ADD_GUI = '/nex/patchbay/add_gui'
CONNECT = '/nex/patchbay/connect'
DISCONNECT = '/nex/patchbay/disconnect'
GROUP_CUSTOM_NAME = '/nex/patchbay/group_custom_name'
GUI_DISANNOUNCE = '/nex/patchbay/gui_disannounce'
PORT_CUSTOM_NAME = '/nex/patchbay/port_custom_name'
REFRESH = '/nex/patchbay/refresh'
SAVE_GROUP_CUSTOM_NAME = '/nex/patchbay/save_group_custom_name'
SAVE_PORT_CUSTOM_NAME = '/nex/patchbay/save_port_custom_name'
ENABLE_JACK_PRETTY_NAMING = '/nex/patchbay/enable_jack_pretty_naming'
EXPORT_ALL_CUSTOM_NAMES = '/nex/patchbay/export_all_custom_names'
IMPORT_ALL_PRETTY_NAMES = '/nex/patchbay/import_all_pretty_names'
CLEAR_ALL_PRETTY_NAMES = '/nex/patchbay/clear_all_pretty_names'
SET_BUFFER_SIZE = '/nex/patchbay/set_buffer_size'
TRANSPORT_PLAY = '/nex/patchbay/transport_play'
TRANSPORT_RELOCATE = '/nex/patchbay/transport_relocate'
TRANSPORT_STOP = '/nex/patchbay/transport_stop'