
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



IS_STARTED = '/nex/gui/preview/client/is_started'
NEX_HACK_UPDATE = '/nex/gui/preview/client/nex_hack_update'
NEX_NET_UPDATE = '/nex/gui/preview/client/nex_net_update'
UPDATE = '/nex/gui/preview/client/update'