
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



CLIENT_EVENT = '/nex/monitor/client_event'
CLIENT_STATE = '/nex/monitor/client_state'
CLIENT_UPDATED = '/nex/monitor/client_updated'