
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



CLEAR_ABSENTS_IN_VIEW = '/nex/server/patchbay/clear_absents_in_view'
SAVE_GROUP_POSITION = '/nex/server/patchbay/save_group_position'
SAVE_GROUP_CUSTOM_NAME = '/nex/server/patchbay/save_group_custom_name'
SAVE_PORT_CUSTOM_NAME = '/nex/server/patchbay/save_port_custom_name'
SAVE_PORTGROUP = '/nex/server/patchbay/save_portgroup'
VIEW_NUMBER_CHANGED = '/nex/server/patchbay/view_number_changed'
VIEW_PTV_CHANGED = '/nex/server/patchbay/view_ptv_changed'
VIEWS_CHANGED = '/nex/server/patchbay/views_changed'