
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



AUTO_SNAPSHOT = '/nex/gui/session/auto_snapshot'
DUPLICATE_ONLY = '/nex/gui/session/duplicate_only'
IS_NSM = '/nex/gui/session/is_nsm'
NAME = '/nex/gui/session/name'
NOTES = '/nex/gui/session/notes'
NOTES_HIDDEN = '/nex/gui/session/notes_hidden'
NOTES_SHOWN = '/nex/gui/session/notes_shown'
RENAMEABLE = '/nex/gui/session/renameable'
SORT_CLIENTS = '/nex/gui/session/sort_clients'