
# This file has been generated by src/utils/osc_paths/path_makers.py.
# Do not edit it, edit 'all_paths' file and run 'path_makers.py'.



ADD = '/nex/gui/trash/add'
CLEAR = '/nex/gui/trash/clear'
NEX_HACK_UPDATE = '/nex/gui/trash/nex_hack_update'
NEX_NET_UPDATE = '/nex/gui/trash/nex_net_update'
REMOVE = '/nex/gui/trash/remove'